name: Python lint

on:
  push:
    branches:
      - main
      - devel-*
  pull_request:
    branches: [ main ]

env:
  SEMGREP_RULES: >-  # https://semgrep.dev/explore
    p/security-audit
    p/secrets
    p/flask
    p/python

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.python-version}}

    - name: Install with poetry
      run: |
        sudo apt install python3-dev  # for compiling things
        sudo apt install libpango-1.0-0 libharfbuzz0b libpangoft2-1.0-0  # For HTML -> PDF
        sudo apt install libreoffice-base-nogui libreoffice-calc-nogui libreoffice-draw-nogui libreoffice-impress-nogui libreoffice-math-nogui libreoffice-writer-nogui  # For Office -> PDF
        sudo apt install exiftool  # for extracting exif information
        python -m pip install --upgrade pip poetry
        poetry install
        poetry add pylint

    - name: Install test dependencies
      run: |
        python -m pip install flake8 black bandit mypy lxml pylint semgrep
    - name: bandit
      run: |
        bandit -r .
      if: ${{ always() }}
    - name: black
      run: |
        black --diff --check .
      if: ${{ always() }}
    - name: codespell
      uses: codespell-project/actions-codespell@master
      with:
        ignore_words_file: .codespellignore
      if: ${{ always() }}
    - name: flake8
      run: |
        flake8 . --show-source --statistics
      if: ${{ always() }}
    - name: pylint
      run: |
        poetry run pylint -ry bin pandora tools website
      if: ${{ always() }}
    - name: semgrep
      run: |
        semgrep --config auto
      if: ${{ always() }}
